In [1]:
import time
from keras.utils import np_utils
from keras.models import Sequential

#from keras.optimizers import SGBD
from tensorflow.keras.optimizers import SGD
from keras.layers import Input, Dense, Activation

from keras.layers import Input, Dense, Flatten, Dropout, Concatenate, Conv1D, Activation
#from keras.layers.normalization import BatchNormalization

import numpy as np



from sklearn.datasets import load_breast_cancer
from sklearn import preprocessing

Using TensorFlow backend.


ImportError: No module named 'sklearn'

In [9]:
data = load_breast_cancer()

In [10]:
X = data.data
np.shape(X)

(569, 30)

In [11]:
y = data.target
np.shape(y)

(569,)

In [14]:
def normalized(X):
  return (X- np.mean(X, axis=0))/(np.max(X, axis=0) - np.min(X, axis=0))

In [16]:
print(X)
x_norm = normalized(X)
print("after normalization")
print(x_norm)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
after normalization
[[ 0.18281548 -0.30130702  0.21305346 ...  0.51819167  0.33515559
   0.22926789]
 [ 0.30492254 -0.05139156  0.28284822 ...  0.24533944 -0.02971727
   0.03328206]
 [ 0.26327362  0.06629528  0.26280814 ...  0.44121573  0.14039903
   0.02383696]
 ...
 [ 0.11702912  0.29727262  0.11285306 ...  0.0934494  -0.13458618
  -0.03768738]
 [ 0.30634239  0.3395452   0.33260291 ...  0.5168171   0.23383487
   0.26271929]
 [-0.3013532   0.1775567  -0.30439523 ... -0.39383582 -0.00586551
  -0.08891393]]


In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_norm,y , test_size=0.3, train_size=0.7, random_state=True)
x_validation, x_test, 

In [ ]:
from keras.layers import Dense, Activation
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
#from keras.layers.normalization import BatchNormalization

# import BatchNormalization
from tensorflow.keras.layers import BatchNormalization



learning_rate =0.8
batch_size = 50
nb_epoch =50

#hyperparametre deep_learning, tableau (colone, ligne (accuracy, loss))
#ammelioer cet modele
model = Sequential()
model.add(Dense(128, input_dim=30))
model.add(Activation('sigmoid'))
model.add(Dropout(0.3))

model.add(Dense(512))
model.add(Activation('sigmoid'))
model.add(Dropout(0.3))
model.add(BatchNormalization())


model.add(Dense(1))
model.add(Activation('softmax'))

#sauvgarder le bon model
checkpointer = ModelCheckpoint(filepath='NN_TP1.hdf5', monitor='val_loss', verbose=0, save_best_only=True, 
                               save_weiths_only=False, mode='min', period=1)

#toper des qu'il y a une divergence
early = EarlyStopping(monitor='val_loss', min_delta=0, patience=5, verbose=0, mode='auto')


sgd = SGD(learning_rate)

model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=batch_size, 
          validation_data=(X_validation, y_validation), callbacks=[checkpointer, early] , verbose=1)

In [20]:
np.shape(X_train), np.shape(y_train)

((398, 30), (398,))

In [30]:
from keras.layers import Dense, Activation
from tensorflow.keras.optimizers import SGD

learning_rate =0.8
batch_size = 50
nb_epoch =50

#hyperparametre deep_learning, tableau (colone, ligne (accuracy, loss))
model = Sequential()
model.add(Dense(128, input_dim=30))
model.add(Activation('sigmoid'))
model.add(Dropout(0.3))

model.add(Dense(512))
model.add(Activation('sigmoid'))
model.add(Dropout(0.3))



model.add(Dense(1))
model.add(Activation('softmax'))

sgd = SGD(learning_rate)
model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=batch_size, epochs=nb_epoch, verbose=1)

Epoch 1/50
8/8 [==============================] - 1s 4ms/step - loss: 5.8756 - accuracy: 0.6256
Epoch 2/50
8/8 [==============================] - 0s 4ms/step - loss: 1.6251 - accuracy: 0.6256
Epoch 3/50
8/8 [==============================] - 0s 4ms/step - loss: 0.7074 - accuracy: 0.6256
Epoch 4/50
8/8 [==============================] - 0s 4ms/step - loss: 0.7874 - accuracy: 0.6256
Epoch 5/50
8/8 [==============================] - 0s 5ms/step - loss: 0.6896 - accuracy: 0.6256
Epoch 6/50
8/8 [==============================] - 0s 5ms/step - loss: 0.6585 - accuracy: 0.6256
Epoch 7/50
8/8 [==============================] - 0s 4ms/step - loss: 0.6924 - accuracy: 0.6256
Epoch 8/50
8/8 [==============================] - 0s 4ms/step - loss: 0.8237 - accuracy: 0.6256
Epoch 9/50
8/8 [==============================] - 0s 4ms/step - loss: 0.6683 - accuracy: 0.6256
Epoch 10/50
8/8 [==============================] - 0s 5ms/step - loss: 0.6808 - accuracy: 0.6256
Epoch 11/50
8/8 [======================

Régression Logistique
**texte en gras**

In [38]:
from keras.layers import Dense, Activation
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
#from keras.layers.normalization import BatchNormalization

# import BatchNormalization
from tensorflow.keras.layers import BatchNormalization



learning_rate =0.8
batch_size = 50
nb_epoch =50

#hyperparametre deep_learning, tableau (colone, ligne (accuracy, loss))
#ammelioer cet modele
model = Sequential()
model.add(Dense(128, input_dim=30))
model.add(Activation('sigmoid'))
model.add(Dropout(0.3))

model.add(Dense(512))
model.add(Activation('sigmoid'))
model.add(Dropout(0.3))
model.add(BatchNormalization())


model.add(Dense(1))
model.add(Activation('softmax'))

#sauvgarder le bon model
checkpointer = ModelCheckpoint(filepath='NN_TP1.hdf5', monitor='val_loss', verbose=0, save_best_only=True, 
                               save_weiths_only=False, mode='min', period=1)

#toper des qu'il y a une divergence
early = EarlyStopping(monitor='val_loss', min_delta=0, patience=5, verbose=0, mode='auto')


sgd = SGD(learning_rate)

model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=batch_size, callbacks=[checkpointer, early], verbose=1)

8/8 [==============================] - 1s 6ms/step - loss: 1.1618 - accuracy: 0.6256
